version: 1
validation: sovereign
accounts: 
- name: alice
  coins:
  - 20000token
  - 1000000000000stake 
- name: bob
  coins:
  - 10000token
  - 500000000000stake  
client:
  openapi:
    path: docs/static/openapi.yml
faucet:
  name: bob
  coins:
  - 5token
  - 100000000stake
validators:
- name: alice
  bonded: 900000000000stake  