version: '3'

services:
  validator1:

    build: .
    container_name: blog-validator1
    ports:
      - "26656:26656"  # P2P
      - "26657:26657"  # RPC
      - "1317:1317"    # REST
      - "9090:9090"    # GRPC
    volumes:
      - ./validator1-data:/root/.blog
      - ./shared:/shared
    environment:
      - MONIKER=validator1
        command: |
      bash -c '
      if [[ ! -f /root/.blog/config/genesis.json ]] || [[ ! -f /root/.blog/config/priv_validator_key.json ]]; then
        echo "First time initialization for validator1..."
        
        # First time initialization
        blogd init validator1 --chain-id blog-testnet --overwrite
        blogd keys add alice --keyring-backend test
        ADDR=$$(blogd keys show alice -a --keyring-backend test)
        echo $$ADDR > /shared/validator1_address
        
        while [[ ! -f /shared/validator2_address ]]; do
          echo "Waiting for other validators to initialize..."
          sleep 1
        done
        
        blogd genesis add-genesis-account $$ADDR 1000000000000stake,1000000000000token
        VAL_VALIDATOR2_ADDR=$$(cat /shared/validator2_address)
        blogd genesis add-genesis-account $$VAL_VALIDATOR2_ADDR 1000000000000stake,1000000000000token
        
        # Share genesis and create gentx
        cp /root/.blog/config/genesis.json /shared/genesis.json
        echo "true" > /shared/genesis_accounts_ready
        blogd genesis gentx alice 900000000000stake --chain-id blog-testnet --keyring-backend test
        cp /root/.blog/config/gentx/*.json /shared/validator1_gentx.json
        
        # Wait for other validators gentxs
        while [[ ! -f /shared/validator2_gentx.json ]]; do
          echo "Waiting for other validators gentxs..."
          sleep 1
        done
        
        # Collect gentxs and create final genesis
        mkdir -p /root/.blog/config/gentx
        cp /shared/validator2_gentx.json /root/.blog/config/gentx/
        blogd genesis collect-gentxs
        cp /root/.blog/config/genesis.json /shared/final_genesis.json
        echo "true" > /shared/setup_complete
      else
        echo "validator1 already initialized, starting chain..."
      fi
      
      # Set gas prices and start chain
      sed -i "s/minimum-gas-prices = \"\"/minimum-gas-prices = \"0.00001stake\"/" /root/.blog/config/app.toml
      blogd start --minimum-gas-prices=0.00001stake'
  validator2:

    build: .
    container_name: blog-validator2
    ports:
      - "26666:26656"  # P2P
      - "26667:26657"  # RPC
      - "1327:1317"    # REST
      - "9092:9090"    # GRPC
    volumes:
      - ./validator2-data:/root/.blog
      - ./shared:/shared
    environment:
      - MONIKER=validator2
        depends_on:
      - validator1
    command: |
      bash -c '
      if [[ ! -f /root/.blog/config/genesis.json ]] || [[ ! -f /root/.blog/config/priv_validator_key.json ]]; then
        echo "First time initialization for validator2..."
        
        # First time initialization
        blogd init validator2 --chain-id blog-testnet --overwrite
        blogd keys add bob --keyring-backend test
        ADDR=$$(blogd keys show bob -a --keyring-backend test)
        echo $$ADDR > /shared/validator2_address
        
        # Wait for genesis file
        while [[ ! -f /shared/genesis_accounts_ready ]]; do
          echo "Waiting for genesis accounts..."
          sleep 1
        done
        
        # Copy genesis and create gentx
        cp /shared/genesis.json /root/.blog/config/genesis.json
        blogd genesis gentx bob 900000000000stake --chain-id blog-testnet --keyring-backend test
        cp /root/.blog/config/gentx/*.json /shared/validator2_gentx.json
        
        # Wait for final genesis
        while [[ ! -f /shared/final_genesis.json ]]; do
          echo "Waiting for final genesis..."
          sleep 1
        done
        cp /shared/final_genesis.json /root/.blog/config/genesis.json
      else
        echo "validator2 already initialized, starting chain..."
      fi
      
      # Set gas prices and start chain
      sed -i "s/minimum-gas-prices = \"\"/minimum-gas-prices = \"0.00001stake\"/" /root/.blog/config/app.toml
      while [[ ! -f /shared/setup_complete ]]; do
        echo "Waiting for setup to complete..."
        sleep 1
      done
      blogd start --minimum-gas-prices=0.00001stake'

networks:
  default:
    name: blog-network